---
- name: Install reqs for Docker
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
#      - python3-requests
    state: latest
    update_cache: yes

- name: Add the GPG key for Docker
  shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'

- name: Add the repository
  shell: 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable" | tee /etc/apt/sources.list.d/docker.list'

- name: Update and install docker
  ansible.builtin.apt:
    update_cache: yes
    name: docker-ce
    state: latest

- name: Install the Docker module for Python
  pip:
    name:
      - docker
  notify: docker systemd

- name: revert requests to 2.31.0 to bypass https://github.com/docker/docker-py/issues/3256
  ansible.builtin.command:
    cmd: pip install --force-reinstall requests==2.31.0

- name: Chmod 666 docker.sock
  ansible.builtin.file:
    path: /var/run/docker.sock
    state: file
    owner: 1000
    group: 1000
    mode: 0666

- name: Create dir for data
  ansible.builtin.file:
    path: /etc/elasticsearch/data
    state: directory
    owner: 1000
    group: 1000
    mode: 0775

- name: Create container
  docker_container:
    name: "Elasticsearch"
    image: "bitnami/elasticsearch:latest"
    user: 1000
    volumes:
    - "/etc/elasticsearch/data:/bitnami/elasticsearch/data"
    ports:
    - "9200:9200"
    - "9300:9300"
    env:
        ELASTICSEARCH_CLUSTER_NAME=diplom
        xpack.security.enrollment.enabled=true
    state: started
    restart_policy: always

- name: docker container ls -la
  tags: container_ls
  shell: "docker container ls -la"
  register: container_info
 
- name: docker container ls -la result
  tags: container_ls
  debug:
    msg: "{{container_info.stdout_lines}}"

